image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

# Install node libraries
before_script:
  - cd client/
  - npm install
  - cd ..
  - cd server/
  - npm install
  - cd ..

build_client:
  stage: build
  script:
    - cd client/
    - npm run build-prod
    - cd ..

test_server:
  stage: test
  script:
    - cd server/
    - npm run test
    - cd ..